# Site settings
title:          Dominik Holek
description:    "My personal blog and bio."
url:            "https://darksoothingshadow.github.io"
baseurl: ""

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Dominik Holek
  url:          https://holekdom.me
  email:        holekdom@gmail.com

# Profile information
profile:
  github: https://github.com/darksoothingshadow
  linkedin: https://www.linkedin.com/in/dominikholek/0

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale